/**
 * AUTO-GENERATED by scripts/generate-api-tester-endpoints.mjs
 * Do not edit by hand — re-run after adding/removing API routes.
 *
 * Only routes that exist AND accept customer API keys (authenticateApiKey).
 * Session-only / admin-only routes are excluded (they fail when the Tester
 * sends hl_live_/hl_test_ as Bearer).
 */

export type GeneratedEndpoint = {
  group: string;
  method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
  path: string;
};

export const GENERATED_ENDPOINTS: GeneratedEndpoint[] = [
  { group: "API Keys", method: "GET", path: "/api/apikeys/whoami" },
];

export const GENERATED_ENDPOINT_COUNT = 1;
