/**
 * AUTO-GENERATED by scripts/generate-api-tester-endpoints.mjs
 * Do not edit by hand — re-run the script after adding/removing API routes.
 */

export type GeneratedEndpoint = {
  group: string;
  method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
  path: string;
};

export const GENERATED_ENDPOINTS: GeneratedEndpoint[] = [
  { group: "Admin", method: "GET", path: "/api/admin/analytics" },
  { group: "Admin", method: "GET", path: "/api/admin/apikeys" },
  { group: "Admin", method: "GET", path: "/api/admin/applications" },
  { group: "Admin", method: "DELETE", path: "/api/admin/applications/:id" },
  { group: "Admin", method: "PATCH", path: "/api/admin/applications/:id" },
  { group: "Admin", method: "POST", path: "/api/admin/applications/:id/rotate" },
  { group: "Admin", method: "POST", path: "/api/admin/bootstrap-promote" },
  { group: "Admin", method: "GET", path: "/api/admin/health" },
  { group: "Admin", method: "GET", path: "/api/admin/logs" },
  { group: "Admin", method: "GET", path: "/api/admin/organizations" },
  { group: "Admin", method: "DELETE", path: "/api/admin/organizations/:id" },
  { group: "Admin", method: "GET", path: "/api/admin/organizations/:id" },
  { group: "Admin", method: "PATCH", path: "/api/admin/organizations/:id" },
  { group: "Admin", method: "GET", path: "/api/admin/overview" },
  { group: "Admin", method: "GET", path: "/api/admin/settings" },
  { group: "Admin", method: "PATCH", path: "/api/admin/settings" },
  { group: "Admin", method: "POST", path: "/api/admin/tester/execute" },
  { group: "Admin", method: "POST", path: "/api/admin/tester/validate" },
  { group: "Admin", method: "GET", path: "/api/admin/users" },
  { group: "Admin", method: "DELETE", path: "/api/admin/users/:id" },
  { group: "Admin", method: "PATCH", path: "/api/admin/users/:id" },
  { group: "Admin", method: "POST", path: "/api/admin/users/:id/reset-password" },
  { group: "API Keys", method: "GET", path: "/api/apikeys" },
  { group: "API Keys", method: "POST", path: "/api/apikeys" },
  { group: "API Keys", method: "DELETE", path: "/api/apikeys/:id" },
  { group: "API Keys", method: "POST", path: "/api/apikeys/:id/disable" },
  { group: "API Keys", method: "POST", path: "/api/apikeys/:id/rotate" },
  { group: "API Keys", method: "GET", path: "/api/apikeys/whoami" },
  { group: "Auth", method: "POST", path: "/api/auth/login" },
  { group: "Auth", method: "POST", path: "/api/auth/logout" },
  { group: "Auth", method: "GET", path: "/api/auth/me" },
  { group: "Auth", method: "POST", path: "/api/auth/refresh" },
  { group: "Auth", method: "POST", path: "/api/auth/register" },
  { group: "Brain", method: "POST", path: "/api/brain/ask" },
  { group: "Brain", method: "GET", path: "/api/brain/conversations" },
  { group: "Brain", method: "DELETE", path: "/api/brain/conversations/:id" },
  { group: "Brain", method: "GET", path: "/api/brain/conversations/:id" },
  { group: "Brain", method: "PATCH", path: "/api/brain/conversations/:id" },
  { group: "Organizations", method: "GET", path: "/api/organizations" },
  { group: "Organizations", method: "POST", path: "/api/organizations" },
  { group: "Organizations", method: "GET", path: "/api/organizations/plans" },
  { group: "Organizations", method: "POST", path: "/api/organizations/subscriptions/change-plan" },
  { group: "Organizations", method: "GET", path: "/api/organizations/usage" },
  { group: "Projects", method: "GET", path: "/api/projects" },
  { group: "Projects", method: "POST", path: "/api/projects" },
];

export const GENERATED_ENDPOINT_COUNT = 45;
